# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests.

name: Build and Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false
      record_tests:
        type: boolean
        description: "Record the tests with Cypress Dashboard (https://docs.cypress.io/guides/dashboard/introduction)"
        required: false
        default: false

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_ENV: test
  CYPRESS_USER_EMAIL: ${{ secrets.CYPRESS_USER_EMAIL }}
  CYPRESS_USER_PASSWORD: ${{ secrets.CYPRESS_USER_PASSWORD }}

jobs:
  build:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: ./pnpm-lock.yaml
          
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
